### ISSUE TITLE
Getting started conf.json missing

### ISSUE THREAD

**Issue by jakubmatyszewski** [akamai/luda#1]
Hi,
I have some trouble with _getting started_ since after running docker-compose and copying the `test/data_demo.csv` to container's data folder it seems like `conf.json` is missing - even though readme states:
> The file conf.json is already set like we need. 

Moreover, even when trying to run the script with config file based on config that is mentioned in section that explains setting it to run regex it seems like getting started code is missing pieces - eg. I get errors on some assertions, with first example being first `data` step - assertion ```assert list(df) == list(Url.__annotations__)``` will throw an exception, since `list(df)` should return `[url, label]` or even `[url]` (since it is mentioned that the `url` is the only mandatory column at this point) but `list(Url.__annotations__` will return `[url,source,label,family]` so assertion raises an error.

I'm not sure if I'm missing something here, but would greatly appreciate your help, perhaps providing more "out of the box" example to check out the library outcome.

Thanks in advance!

**Comment by JordanGarzon** [comment]
Hey ,

I committed "config.json" thank you for noticing.

For the data step , are you trying to add your own sources by adding them to "additional_files" ?

**Comment by jakubmatyszewski** [comment]
Thank you! So I wasn't that far with my previous `config.json`. Anyway, I've started once again with config file you provided and followed the instructions step by step.
First trouble I encounter is when running `python main.py` via `docker exec -it luda bash`, it ends up with:
> 2021-08-18 11:52:42,041 - preprocessor_basic - INFO - We did not find /code/data/regex_list.json. We skip the cleaning with regexes step.

And an error `FileNotFoundError: [Errno 2] No such file or directory: '/code/data/regex_list.json'`, since in `preprocessor_basic.py` there is an _if_ statement to catch case when regex list file is missing, however it only prints log info and lets the method to run further and it results with error I've just mentioned since logging doesn't interrupt script execution in contrast to raising an exception. This can be fixed by adding _else_ (when file exists):

```python
def clean_with_regexes(self, df):
        if not os.path.exists(conf.LAST_REGEX_LIST):
            logger.info('We did not find {}. We skip the cleaning with regexes step'.format(conf.LAST_REGEX_LIST))
        else:
            with open(conf.LAST_REGEX_LIST) as json_file:
                regex_list = json.load(json_file)['regexes']
            already_found = self.regex_test(regex_list, list(df[df['path'].notnull()]['path'].unique()))[0]
            logger.info('{} paths are already found with the old regexes'.format(len(already_found)))
            df = df[~df['path'].isin(list(already_found))]
        return df
```
This way we skip cleaning with regexes and in fact we can move on with further steps on the _getting started_.

---
Back to `data` step, it's similar thing happening here. I have previously omitted `additional_files` in config.json:
```json
{
  "main_file": "data_demo.csv",
  "data": {
    "run": true,
    "additional_files": []
  },
  (...)
}
```
However it shouldn't matter here I guess, since error happens before even calling `additional_sources` variable. When I run the script with this configuration I end up with following error:
```
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main()
  File "main.py", line 26, in main
    UseCaseData().run(main_file, config['data']['additional_files'])
  File "/code/src/use_case/use_case_data.py", line 17, in run
    assert list(df) == list(Url.__annotations__)
AssertionError
```

This happens because the `main_file` has wrong headlines (as I mentioned before - list(df) should result with at least `['url']`, however `Url` object declared in `src/feeder/feed_downloader.py` returns following annotations: `url, source, label, family`).  So all I wanted to point out here is that the code is inconsistent with description in the _getting started_, where it is stated that file with `url` column should be sufficient.

Hope remarks I've made are clear, let me know if there is something I perhaps interpreted in a wrong way or something is not clear.

Anyway, with the `config.json` and after fixing few errors/exceptions like this I think I will be able to fully test this package, so thank you for your work!

**Comment by JordanGarzon** [comment]
Hey,

First all, the first point about the old regexes is clearly something that I missed. Thanks for noticing. 

About the second point, I did a quick fix by filling all columns in `data_demo.csv`. About the inconsistant statement saying "url should be sufficient" I thought people will add their files only from the` additional_files`. So I clarified that point in the Readme. 
To summarize the status for now. 2 ways to add your files:

1. Provide directly the `main file` and you need to fill all columns
2. Provide files from `additional_files` and them you need only the `url` column. 

If I have a time I'll improve the code to avoid this difference. But for now, everything should work by following the Readme.

I also moved the `config.json` to `test/config.json` by the way. 

Thank you again for noticing those issues.

Jordan
